version: '3.9'

services:
    crud-postgres:
        image: postgres:15-alpine
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: crud_db
